{"name": "testcase", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:12: AssumptionFailure\n>>\tpytest.assume(1==4)\nAssertionError: assert False\n\ntest_assume.py:14: AssumptionFailure\n>>\tpytest.assume(3==0)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:12: AssumptionFailure\nE               >>\tpytest.assume(1==4)\nE               AssertionError: assert False\nE               \nE               test_assume.py:14: AssumptionFailure\nE               >>\tpytest.assume(3==0)\nE               AssertionError: assert False\n\n../../venv/lib/python3.9/site-packages/six.py:702: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "45ba0744-d9d9-4836-af02-41cb4ab46502-attachment.txt", "type": "text/plain"}], "start": 1603086315737, "stop": 1603086315777, "uuid": "a05b5c67-de76-4513-aa36-1b1fc1c8e030", "historyId": "a60e71aa5cb18feb8e8d984bcd78ade3", "testCaseId": "db3b42cf24e5e064638c45ffd5cc230e", "fullName": "testcase.test_assume.TestAssert#testcase", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_assume"}, {"name": "subSuite", "value": "TestAssert"}, {"name": "host", "value": "Yiron.local"}, {"name": "thread", "value": "86675-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_assume"}]}